// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovxsujkraqmtwzyrwvpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92eHN1amtyYXFtdHd6eXJ3dnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzQ4NDMsImV4cCI6MjA3MzUxMDg0M30.PrXRN360k-Y2kLpE4LhF6nwzcIyLVWY5VTiKM1oKJyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});